### ISSUE TITLE
Add expanded name

### ISSUE THREAD

**Issue by ludwigpacifici** [tommybennett/algorithm-mnemonics#1]
Hello @tommybennett 

I am implementing an Emacs version of your algorithm mnemonics. Your CppCon light talk was really cool!

Do you think it makes sense to add a "long description" in the `algorithm_mnemonics.xml`? For example, adding a tag like `en` standing for "expanded name":

```
<p n="mme" en="std::minmax_element">
    <text>
        auto minmax = std::minmax_element(begin(%\m C%), end(%\m C%));
    </text>
</p>
```

If you agree, I don't mind to do a pull request.

**Comment by tommybennett** [comment]
I'm glad you liked the talk.  I use the algorithm mnemonics everyday.  I found them to be invaluable and decided I should tell others about them. I have received lots of positive responses and interest.  

Yes, I agree, that is a great idea to add the expanded name.  Go ahead and issue a pull request.

When you complete the Emacs version, we can add it to an Emacs directory in the algorithm-mnemonics repository, if you prefer.

I have updated the description on the main page.  You may find it useful.

Thank you for your interest.

**Comment by ludwigpacifici** [comment]
I created the repository [algorithm-mnemonics-emacs](https://github.com/ludwigpacifici/algorithm-mnemonics-emacs). It is a clojure script which reads `algorithm_mnemonics.xml` and generates files for [yasnippet](https://github.com/joaotavora/yasnippet) (it is the plugin to expand abbreviations in GNU Emacs). To make these mnemonics available by default with yasnippet, I will ask to put the [generated yasnippet files](https://github.com/ludwigpacifici/algorithm-mnemonics-emacs/tree/master/test) in the repository [yasnippet-snippets](https://github.com/AndreaCrotti/yasnippet-snippets).

Tell me if it makes sense to add the generated yasnippet files in your repository. In the end, it's the XML file which is important.

**Comment by tommybennett** [comment]
I will add a reference link to the algorithm-mnemonics repository README.md file to your repository and yasnippet. People can find it from there.  As you mentioned, the XML file is what is important.

Thank you for your efforts, I'm sure many will benefit.

**Comment by ludwigpacifici** [comment]
Thanks @tommybennett . The pull request for Yasnippet is waiting [here](https://github.com/AndreaCrotti/yasnippet-snippets/pull/163).

**Comment by ludwigpacifici** [comment]
Pull request is done. The mnemonics will be shipped by default by YASnippet.

Thanks!
