### ISSUE TITLE
Documentation not inline with XML file

### ISSUE THREAD

**Issue by ludwigpacifici** [tommybennett/algorithm-mnemonics#2]
Hello again @tommybennett 

I compared `STLInstructionSet.docx` and `algorithm_mnemonics.xml` ; I found some differences:
- `pph` `pop_heap` - not found
- `bns` `binary_search` - not found
- `inc` `includes` - not found
- `lwb` `lower_bound` - not found
- `upb` `upper_bound` - not found
- `eqr` `equal_range` - not found
- `stu` `set_union` - not found
- `std` `set_difference` - not found
- `ipm` `inplace_merge` - not found
- `mov` `move` - not found
- `swp` `swap` - not found
- `mpb` `move_backward` - rename to `mvb`?

**Comment by ludwigpacifici** [comment]
Thanks to the tags "n" and "en", this bash snippet gives a listing of available commands: 

```
grep -P "n=" <path_to_algorithm_mnemonics.xml> | awk -F'"' '{print $2" "$4}' | sort
```

The result could be dumped in a markdown file. Then the documentation will be generated only from `algorithm_mnemonics.xml`. Do you think a markdown documentation will be better? However, there will be no subsections like in the `STLInstructionSet.docx`.

**Comment by tommybennett** [comment]
Yes, that is cool.  Automated documentation and keep from repeating the same information in two different places.  Everyone can display markdown, also.  

The -P switch to grep didn't work on my Mac, though.  Seems to be a common issue on Mac from web search.  I was able to get it to work without the -P, though.

I will add the missing algorithms this week to the XML file.

**Comment by ludwigpacifici** [comment]
My mistake, `-P` for `grep` is not required as there is no regexp.

**Comment by tommybennett** [comment]
I added the missing algorithm mnemonics to the XML document and created a documentation script to automatically create the documentation from the XML document.
