### ISSUE TITLE
Vim snippets

### ISSUE THREAD

**Issue by dawikur** [tommybennett/algorithm-mnemonics#7]
Hi @tommybennett,

first of - great! Really great. Also great talk :) I have remapped `CapsLock` to `Ctrl` for over a year and I am using `Ctrl+[` instead of `Esc` for even longer. This really changed my life :+1: 

I did prepare version that is working with snippets engine like https://github.com/SirVer/ultisnips
It lives here: https://github.com/dawikur/algorithm-mnemonics.vim

Maybe you want to start list of implementations?

**Comment by dawikur** [comment]
This is actually not an issue, 
closing.

**Comment by kiryph** [comment]
@tommybennett What about adding a link to the snippets repository of @dawikur to the README.md? I think ultisnips is the right tool for your idea of algorithm-mnemonics in vim.

@dawikur I think using the visual selection feature of ultisnips would be a nice addition to your snippets (https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L774)?

**Comment by dawikur** [comment]
@kiryph 
This looks very cool, I will make use of them.

**Comment by tommybennett** [comment]
@dawikur I know exactly what you mean, Ctrl-Left-[ changed my life, too.  I was about to give up on using vim editing until I discovered ^[.  I no longer notice the different modes.  It is a game changer.

@kiryph I have added a link to the vim ultisnips implementation to the README.md.

Thank you for your interest.
